import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    tutorial: 'Start',
    servers: 'My Servers',
    hosting: 'Server Store',
    learning: 'Learning Center',
    balance: 'Balance',
    income: 'Income/min',
    serverLimit: 'Server Limit',
    startJob: 'Start Job',
    completeJob: 'Complete Job',
    purchaseServer: 'Purchase Server',
    deleteServer: 'Delete Server',
    toggleServer: 'Toggle Server',
    online: 'Online',
    offline: 'Offline',
    settings: 'Settings',
    logout: 'Logout',
    login: 'Login',
    register: 'Register',
    nickname: 'Nickname',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    loggingIn: 'Logging in...',
    creatingAccount: 'Creating Account...',
    loginFailed: 'Login Failed',
    registrationFailed: 'Registration Failed',
    passwordsDoNotMatch: 'Passwords do not match',
    heroTitle: 'Build Your Server Empire',
    heroSubtitle: 'Master the Art of Hosting',
    heroDescription: 'Start with nothing and build the largest server hosting empire in the virtual world. Master economics, technology, and strategy.',
    startPlaying: 'Start Playing',
    learnMore: 'Learn More',
    totalPlayers: 'Total Players',
    onlineNow: 'Online Now',
    serversHosted: 'Servers Hosted',
    totalBalance: 'Total Balance',
    gameFeatures: 'Game Features',
    featuresDescription: 'Discover what makes our server hosting simulator unique',
    feature1Title: 'Build Servers',
    feature1Desc: 'Create and customize your own servers',
    feature2Title: 'Global Network',
    feature2Desc: 'Expand worldwide with data centers',
    feature3Title: 'Grow Revenue',
    feature3Desc: 'Optimize your business for maximum profit',
    feature4Title: 'Fast Performance',
    feature4Desc: 'Deliver lightning-fast hosting services',
    topPlayers: 'Top Players',
    topPlayersDescription: 'See who\'s dominating the hosting industry',
    leaderboard: 'Leaderboard',
    serversLowercase: 'servers',
    joinCompetition: 'Join the Competition',
    allRightsReserved: 'All rights reserved.',
    loginRegister: 'Login / Register',
    // Error messages
    errorNotFound: 'Not Found',
    errorServerError: 'Server Error',
    errorNetworkError: 'Network Error',
    errorUnauthorized: 'Access Denied',
    errorBadRequest: 'Invalid Request',
    errorGeneric: 'Something went wrong',
    pleaseRefresh: 'Please refresh the page and try again',
    jobOnCooldown: 'Job is on cooldown for {seconds} seconds',
    insufficientFunds: 'Insufficient funds',
    serverLimitReached: 'Server limit reached',
    // Tutorial progress
    tutorialProgress: 'Tutorial Progress',
    hideProgress: 'Hide Progress',
    // Game interface elements
    start: 'Start',
    myServers: 'My Servers',
    serverStore: 'Server Store',
    learningCenter: 'Learning Center',
    inProgress: 'In Progress',
    completed: 'Completed',
    active: 'Active',
    available: 'Available',
    unavailable: 'Unavailable',
    locked: 'Locked',
    unlocked: 'Unlocked',
    // Jobs and actions
    tutorialJobs: 'Tutorial Jobs',
    startJob: 'Start Job',
    availableIn: 'Available in',
    earnMoney: 'Earn {amount}',
    cooldownTime: 'Cooldown: {time}',
    // Tutorial tips
    tutorialTips: 'Tutorial Tips',
    tipCompleteJobs: 'Complete jobs to earn money and gain experience',
    tipJobCooldown: 'Each job has a cooldown period before you can do it again',
    tipEarnToUnlock: 'Earn {amount} to unlock servers, learning, and the store',
    tipPurchaseServers: 'Purchase servers to generate passive income',
    tipTakeCourses: 'Take learning courses to unlock more server slots',
    browseServerStore: 'Browse Server Store',
    browseLearningCourses: 'Browse Learning Courses',
    // Activities
    recentActivities: 'Recent Activities',
    // Tutorial completion
    tutorialCompleted: 'Tutorial Completed!',
    tutorialCompletedDesc: 'Congratulations! You\'ve unlocked all game features.',
    completeTutorialUnlock: 'Complete Tutorial & Unlock All Features',
    allFeaturesUnlocked: 'All features unlocked!',
    // Job types
    serverMaintenance: 'Server Maintenance',
    performanceOptimization: 'Performance Optimization',
    securityAudit: 'Security Audit',
    // Quest system
    dailyQuests: 'Daily Quests',
    achievements: 'Achievements',
    rankings: 'Rankings',
    claimReward: 'Claim Reward',
    rewardClaimed: 'Reward Claimed',
    questCompleted: 'Quest Completed',
    reward: 'Reward',
    progress: 'Progress',
    // Admin panel
    adminManagement: 'Admin Management',
    selectUser: 'Select User',
    chooseUser: 'Choose User',
    action: 'Action',
    chooseAction: 'Choose Action',
    executeAction: 'Execute Action',
    giveAdmin: 'Give Admin',
    removeAdmin: 'Remove Admin',
    banUser: 'Ban User',
    unbanUser: 'Unban User',
    totalUsers: 'Total Users',
    onlineUsers: 'Online Users',
    totalAdmins: 'Total Admins',
    userList: 'User List',
    superAdminPanel: 'Super Admin Panel',
    adminPanel: 'Admin Panel',
    // Status indicators
    online: 'Online',
    offline: 'Offline',
    // Server products
    basicWebServer: 'Basic Web Server',
    highPerformanceServer: 'High Performance Server',
    databaseServer: 'Database Server',
    cdnServer: 'CDN Server',
    webHosting: 'Web Hosting',
    gamingApps: 'Gaming/Apps',
    storage: 'Storage',
    contentDelivery: 'Content Delivery',
    // Learning courses
    basicServerSetup: 'Basic Server Setup',
    advancedServerManagement: 'Advanced Server Management',
    securityProtocols: 'Security Protocols',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    // Common UI elements
    close: 'Close',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    add: 'Add',
    remove: 'Remove',
    update: 'Update',
    refresh: 'Refresh',
    loading: 'Loading...',
    // Time formats
    minutes: 'minutes',
    hours: 'hours',
    seconds: 'seconds',
    secondsShort: 'sec',
    // Server-specific translations
    serverLimit: 'Server Limit',
    noServersYet: 'No Servers Yet',
    purchaseServersFromStore: 'Purchase servers from the store to start hosting and earning passive income!',
    visitServerStore: 'Visit Server Store',
    // Admin panel translations
    superAdminPanel: 'Super Admin Panel',
    adminPanel: 'Admin Panel', 
    totalUsers: 'Total Users',
    onlineUsers: 'Online Users',
    totalAdmins: 'Total Admins',
    adminManagement: 'Admin Management',
    selectUser: 'Select User',
    chooseUser: 'Choose User',
    action: 'Action',
    chooseAction: 'Choose Action',
    giveAdmin: 'Give Admin',
    removeAdmin: 'Remove Admin',
    banUser: 'Ban User',
    unbanUser: 'Unban User',
    executeAction: 'Execute Action',
    userList: 'User List',
    success: 'Success',
    error: 'Error',
    claiming: 'Claiming...',
    coursesGenitive: 'courses',
    serverSettings: 'Server Settings',
    loadPercentage: 'Load Percentage',
    currentLoad: 'Current Load',
    overloadRisk: 'Overload Risk',
    low: 'Low',
    moderate: 'Moderate',
    high: 'High',
    veryHigh: 'Very High',
    serverShutdownWarning: 'High load increases shutdown risk',
    rentalCost: 'Rental Cost/min',
    // Profile modal
    progressToLevel: 'Progress to Level',
    xpNeeded: 'XP needed',
    totalEarnings: 'Total Earnings',
    totalSpent: 'Total Spent',
    netProfit: 'Net Profit',
    jobsCompleted: 'Jobs Completed',
    coursesCompleted: 'Courses Completed',
    achievement: 'Achievement',
    noAchievementsYet: 'No achievements yet',
    earnAchievementsDesc: 'Complete jobs and reach milestones to earn achievements!',
    currentBalance: 'Current Balance',
    // Level up notification
    levelUp: 'Level Up!',
    levelUpCongrats: 'Congratulations! You\'ve reached level',
    newAbilitiesUnlocked: 'New abilities unlocked!',
    // Tooltips and hints
    profileTooltip: 'Click on your avatar to see progress and other interesting information',
    nicknameTooltip: 'Click on your nickname or someone else\'s to view their profile',
    // Theme system
    darkTheme: 'Dark Theme',
    lightTheme: 'Light Theme',
  },
  ru: {
    tutorial: 'Старт',
    servers: 'Мои серверы',
    hosting: 'Магазин серверов',
    learning: 'Центр обучения',
    myServers: 'Мои серверы',
    serverStore: 'Магазин серверов',
    learningCenter: 'Центр обучения',
    balance: 'Баланс',
    income: 'Доход/мин',
    serverLimit: 'Лимит серверов',
    startJob: 'Начать работу',
    completeJob: 'Завершить работу',
    purchaseServer: 'Купить сервер',
    deleteServer: 'Удалить сервер',
    toggleServer: 'Переключить сервер',
    online: 'Онлайн',
    offline: 'Офлайн',
    settings: 'Настройки',
    logout: 'Выйти',
    login: 'Вход',
    register: 'Регистрация',
    nickname: 'Никнейм',
    password: 'Пароль',
    confirmPassword: 'Подтвердите пароль',
    loggingIn: 'Вход...',
    creatingAccount: 'Создание аккаунта...',
    loginFailed: 'Ошибка входа',
    registrationFailed: 'Ошибка регистрации',
    passwordsDoNotMatch: 'Пароли не совпадают',
    heroTitle: 'Создайте Свою Серверную Империю',
    heroSubtitle: 'Освойте Искусство Хостинга',
    heroDescription: 'Начните с нуля и постройте крупнейшую империю серверного хостинга в виртуальном мире. Изучите экономику, технологии и стратегию.',
    startPlaying: 'Начать Играть',
    learnMore: 'Узнать Больше',
    totalPlayers: 'Всего Игроков',
    onlineNow: 'Сейчас Онлайн',
    serversHosted: 'Серверов Размещено',
    totalBalance: 'Общий Баланс',
    gameFeatures: 'Особенности Игры',
    featuresDescription: 'Узнайте, что делает наш симулятор хостинга уникальным',
    feature1Title: 'Создавайте Серверы',
    feature1Desc: 'Создавайте и настраивайте собственные серверы',
    feature2Title: 'Глобальная Сеть',
    feature2Desc: 'Расширяйтесь по всему миру с дата-центрами',
    feature3Title: 'Увеличивайте Доход',
    feature3Desc: 'Оптимизируйте бизнес для максимальной прибыли',
    feature4Title: 'Высокая Производительность',
    feature4Desc: 'Предоставляйте молниеносно быстрые услуги хостинга',
    topPlayers: 'Топ Игроков',
    topPlayersDescription: 'Посмотрите, кто доминирует в индустрии хостинга',
    leaderboard: 'Таблица Лидеров',
    serversLowercase: 'серверов',
    joinCompetition: 'Присоединиться к Соревнованию',
    allRightsReserved: 'Все права защищены.',
    loginRegister: 'Вход / Регистрация',
    // Error messages
    errorNotFound: 'Не найдено',
    errorServerError: 'Ошибка сервера',
    errorNetworkError: 'Ошибка сети',
    errorUnauthorized: 'Доступ запрещен',
    errorBadRequest: 'Неверный запрос',
    errorGeneric: 'Что-то пошло не так',
    pleaseRefresh: 'Пожалуйста, обновите страницу и попробуйте снова',
    jobOnCooldown: 'Работа недоступна {seconds} секунд',
    insufficientFunds: 'Недостаточно средств',
    serverLimitReached: 'Достигнут лимит серверов',
    // Tutorial progress
    tutorialProgress: 'Прогресс обучения',
    hideProgress: 'Скрыть прогресс',
    // Game interface elements
    start: 'Старт',
    myServers: 'Мои серверы',
    serverStore: 'Магазин серверов',
    learningCenter: 'Центр обучения',
    inProgress: 'В процессе',
    completed: 'Завершено',
    active: 'Активно',
    available: 'Доступно',
    unavailable: 'Недоступно',
    locked: 'Заблокировано',
    unlocked: 'Разблокировано',
    // Jobs and actions
    tutorialJobs: 'Обучающие задания',
    startJob: 'Начать работу',
    availableIn: 'Доступно через',
    earnMoney: 'Заработать {amount}',
    cooldownTime: 'Перезарядка: {time}',
    // Tutorial tips
    tutorialTips: 'Подсказки обучения',
    tipCompleteJobs: 'Выполняйте задания, чтобы заработать деньги и получить опыт',
    tipJobCooldown: 'У каждого задания есть период перезарядки перед повторным выполнением',
    tipEarnToUnlock: 'Заработайте {amount}, чтобы разблокировать серверы, обучение и магазин',
    tipPurchaseServers: 'Покупайте серверы для получения пассивного дохода',
    tipTakeCourses: 'Проходите курсы обучения, чтобы разблокировать больше слотов для серверов',
    browseServerStore: 'Просмотреть магазин серверов',
    browseLearningCourses: 'Просмотреть курсы обучения',
    // Activities
    recentActivities: 'Недавние действия',
    // Tutorial completion
    tutorialCompleted: 'Обучение завершено!',
    tutorialCompletedDesc: 'Поздравляем! Вы разблокировали все возможности игры.',
    completeTutorialUnlock: 'Завершить обучение и разблокировать все возможности',
    allFeaturesUnlocked: 'Все возможности разблокированы!',
    // Quest system
    dailyQuests: 'Ежедневные задания',
    achievements: 'Достижения',
    rankings: 'Рейтинг',
    claimReward: 'Забрать награду',
    rewardClaimed: 'Награда получена',
    questCompleted: 'Задание выполнено',
    reward: 'Награда',
    progress: 'Прогресс',
    // Admin panel
    adminManagement: 'Управление администраторами',
    selectUser: 'Выберите пользователя',
    chooseUser: 'Выберите пользователя',
    action: 'Действие',
    chooseAction: 'Выберите действие',
    executeAction: 'Выполнить действие',
    giveAdmin: 'Выдать администратора',
    removeAdmin: 'Убрать администратора',
    banUser: 'Забанить пользователя',
    unbanUser: 'Разбанить пользователя',
    totalUsers: 'Всего пользователей',
    onlineUsers: 'Онлайн пользователей',
    totalAdmins: 'Всего администраторов',
    userList: 'Список пользователей',
    superAdminPanel: 'Панель супер-администратора',
    adminPanel: 'Панель администратора',
    // Job types
    serverMaintenance: 'Обслуживание сервера',
    performanceOptimization: 'Оптимизация производительности',
    securityAudit: 'Аудит безопасности',
    // Status indicators
    online: 'Онлайн',
    offline: 'Офлайн',
    // Server products
    basicWebServer: 'Базовый веб-сервер',
    highPerformanceServer: 'Высокопроизводительный сервер',
    databaseServer: 'Сервер базы данных',
    cdnServer: 'CDN сервер',
    webHosting: 'Веб-хостинг',
    gamingApps: 'Игры/Приложения',
    storage: 'Хранилище',
    contentDelivery: 'Доставка контента',
    // Learning courses
    basicServerSetup: 'Базовая настройка сервера',
    advancedServerManagement: 'Продвинутое управление сервером',
    securityProtocols: 'Протоколы безопасности',
    beginner: 'Начинающий',
    intermediate: 'Средний',
    advanced: 'Продвинутый',
    // Additional interface elements
    until: 'до',
    hours: 'ч',
    minutes: 'м',
    reset: 'сброс',
    resetAvailable: 'Сброс доступен',
    progressLabel: 'Прогресс',
    earnedLabel: 'Получено',
    completedTasks: 'заданий',
    achievements: 'Достижения',
    // Common UI elements
    close: 'Закрыть',
    cancel: 'Отмена',
    confirm: 'Подтвердить',
    save: 'Сохранить',
    edit: 'Редактировать',
    delete: 'Удалить',
    add: 'Добавить',
    remove: 'Удалить',
    update: 'Обновить',
    refresh: 'Обновить',
    loading: 'Загрузка...',
    // Time formats
    minutes: 'минут',
    hours: 'часов',
    seconds: 'секунд',
    secondsShort: 'сек',
    // Server-specific translations
    serverLimit: 'Лимит серверов',
    noServersYet: 'Серверов пока нет',
    purchaseServersFromStore: 'Покупайте серверы в магазине, чтобы начать хостинг и получать пассивный доход!',
    visitServerStore: 'Посетить магазин серверов',
    // Admin panel translations
    superAdminPanel: 'Супер админ панель',
    adminPanel: 'Админ панель', 
    totalUsers: 'Всего пользователей',
    onlineUsers: 'Онлайн пользователей',
    totalAdmins: 'Всего админов',
    adminManagement: 'Управление админами',
    selectUser: 'Выбрать пользователя',
    chooseUser: 'Выберите пользователя',
    action: 'Действие',
    chooseAction: 'Выберите действие',
    giveAdmin: 'Выдать админку',
    removeAdmin: 'Забрать админку',
    banUser: 'Забанить пользователя',
    unbanUser: 'Разбанить пользователя',
    executeAction: 'Выполнить действие',
    success: 'Успешно',
    error: 'Ошибка',
    claiming: 'Получение...',
    coursesGenitive: 'курсов',
    serverSettings: 'Настройки сервера',
    loadPercentage: 'Процент нагрузки',
    currentLoad: 'Текущая нагрузка',
    overloadRisk: 'Риск перегрузки',
    low: 'Низкий',
    moderate: 'Умеренный',
    high: 'Высокий',
    veryHigh: 'Очень высокий',
    serverShutdownWarning: 'Высокая нагрузка увеличивает риск отключения',
    rentalCost: 'Аренда/мин',
    // Profile modal
    progressToLevel: 'Прогресс до уровня',
    xpNeeded: 'нужно опыта',
    totalEarnings: 'Общий доход',
    totalSpent: 'Потрачено всего',
    netProfit: 'Чистая прибыль',
    jobsCompleted: 'Выполнено работ',
    coursesCompleted: 'Пройдено курсов',
    achievement: 'Достижение',
    noAchievementsYet: 'Пока нет достижений',
    earnAchievementsDesc: 'Выполняйте работы и достигайте целей, чтобы получить достижения!',
    currentBalance: 'Текущий баланс',
    // Level up notification
    levelUp: 'Повышение уровня!',
    levelUpCongrats: 'Поздравляем! Вы достигли уровня',
    newAbilitiesUnlocked: 'Новые способности разблокированы!',
    // Tooltips and hints
    profileTooltip: 'Нажмите на свою аватарку, чтобы увидеть прогресс и другую интересную информацию',
    nicknameTooltip: 'Если нажать на свой ник или чужой, можно заглянуть на чей-то профиль',
    // Theme system
    darkTheme: 'Темная тема',
    lightTheme: 'Светлая тема',
  },
  ua: {
    tutorial: 'Старт',
    servers: 'Мої сервери',
    hosting: 'Магазин серверiв',
    learning: 'Центр навчання',
    balance: 'Баланс',
    income: 'Дохід/хв',
    serverLimit: 'Ліміт серверів',
    startJob: 'Почати роботу',
    completeJob: 'Завершити роботу',
    purchaseServer: 'Купити сервер',
    deleteServer: 'Видалити сервер',
    toggleServer: 'Перемкнути сервер',
    online: 'Онлайн',
    offline: 'Офлайн',
    settings: 'Налаштування',
    logout: 'Вийти',
    login: 'Вхід',
    register: 'Реєстрація',
    nickname: 'Нікнейм',
    password: 'Пароль',
    confirmPassword: 'Підтвердіть пароль',
    loggingIn: 'Вхід...',
    creatingAccount: 'Створення акаунту...',
    loginFailed: 'Помилка входу',
    registrationFailed: 'Помилка реєстрації',
    passwordsDoNotMatch: 'Паролі не співпадають',
    heroTitle: 'Створіть Свою Серверну Імперію',
    heroSubtitle: 'Опануйте Мистецтво Хостингу',
    heroDescription: 'Почніть з нуля і збудуйте найбільшу імперію серверного хостингу у віртуальному світі. Вивчіть економіку, технології та стратегію.',
    startPlaying: 'Почати Гру',
    learnMore: 'Дізнатися Більше',
    totalPlayers: 'Всього Гравців',
    onlineNow: 'Зараз Онлайн',
    serversHosted: 'Серверів Розміщено',
    totalBalance: 'Загальний Баланс',
    gameFeatures: 'Особливості Гри',
    featuresDescription: 'Дізнайтеся, що робить наш симулятор хостингу унікальним',
    feature1Title: 'Створюйте Сервери',
    feature1Desc: 'Створюйте та налаштовуйте власні сервери',
    feature2Title: 'Глобальна Мережа',
    feature2Desc: 'Розширюйтеся по всьому світу з дата-центрами',
    feature3Title: 'Збільшуйте Дохід',
    feature3Desc: 'Оптимізуйте бізнес для максимального прибутку',
    feature4Title: 'Висока Продуктивність',
    feature4Desc: 'Надавайте блискавично швидкі послуги хостингу',
    topPlayers: 'Топ Гравців',
    topPlayersDescription: 'Подивіться, хто домінує в індустрії хостингу',
    leaderboard: 'Таблиця Лідерів',
    serversLowercase: 'серверів',
    joinCompetition: 'Приєднатися до Змагання',
    allRightsReserved: 'Всі права захищені.',
    loginRegister: 'Вхід / Реєстрація',
    // Error messages
    errorNotFound: 'Не знайдено',
    errorServerError: 'Помилка сервера',
    errorNetworkError: 'Помилка мережі',
    errorUnauthorized: 'Доступ заборонено',
    errorBadRequest: 'Неправильний запит',
    errorGeneric: 'Щось пішло не так',
    pleaseRefresh: 'Будь ласка, оновіть сторінку та спробуйте знову',
    jobOnCooldown: 'Робота недоступна {seconds} секунд',
    insufficientFunds: 'Недостатньо коштів',
    serverLimitReached: 'Досягнуто ліміт серверів',
    // Tutorial progress
    tutorialProgress: 'Прогрес навчання',
    hideProgress: 'Приховати прогрес',
    // Game interface elements
    start: 'Старт',
    myServers: 'Мої сервери',
    serverStore: 'Магазин серверів',
    learningCenter: 'Центр навчання',
    inProgress: 'В процесі',
    completed: 'Завершено',
    active: 'Активно',
    available: 'Доступно',
    unavailable: 'Недоступно',
    locked: 'Заблоковано',
    unlocked: 'Розблоковано',
    // Jobs and actions
    tutorialJobs: 'Навчальні завдання',
    startJob: 'Почати роботу',
    availableIn: 'Доступно через',
    earnMoney: 'Заробити {amount}',
    cooldownTime: 'Перезарядка: {time}',
    // Tutorial tips
    tutorialTips: 'Підказки навчання',
    tipCompleteJobs: 'Виконуйте завдання, щоб заробити гроші та отримати досвід',
    tipJobCooldown: 'У кожного завдання є період перезарядки перед повторним виконанням',
    tipEarnToUnlock: 'Заробіть {amount}, щоб розблокувати сервери, навчання та магазин',
    tipPurchaseServers: 'Купуйте сервери для отримання пасивного доходу',
    tipTakeCourses: 'Проходьте курси навчання, щоб розблокувати більше слотів для серверів',
    browseServerStore: 'Переглянути магазин серверів',
    browseLearningCourses: 'Переглянути курси навчання',
    // Activities
    recentActivities: 'Недавні дії',
    // Tutorial completion
    tutorialCompleted: 'Навчання завершено!',
    tutorialCompletedDesc: 'Вітаємо! Ви розблокували всі можливості гри.',
    completeTutorialUnlock: 'Завершити навчання та розблокувати всі можливості',
    allFeaturesUnlocked: 'Всі можливості розблоковані!',
    // Job types
    serverMaintenance: 'Обслуговування сервера',
    performanceOptimization: 'Оптимізація продуктивності',
    securityAudit: 'Аудит безпеки',
    // Status indicators
    online: 'Онлайн',
    offline: 'Офлайн',
    // Server products
    basicWebServer: 'Базовий веб-сервер',
    highPerformanceServer: 'Високопродуктивний сервер',
    databaseServer: 'Сервер бази даних',
    cdnServer: 'CDN сервер',
    webHosting: 'Веб-хостинг',
    gamingApps: 'Ігри/Додатки',
    storage: 'Сховище',
    contentDelivery: 'Доставка контенту',
    // Learning courses
    basicServerSetup: 'Базове налаштування сервера',
    advancedServerManagement: 'Просунуте управління сервером',
    securityProtocols: 'Протоколи безпеки',
    beginner: 'Початківець',
    intermediate: 'Середній',
    advanced: 'Просунутий',
    // Common UI elements
    close: 'Закрити',
    cancel: 'Скасувати',
    confirm: 'Підтвердити',
    save: 'Зберегти',
    edit: 'Редагувати',
    delete: 'Видалити',
    add: 'Додати',
    remove: 'Видалити',
    update: 'Оновити',
    refresh: 'Оновити',
    loading: 'Завантаження...',
    // Time formats
    minutes: 'хвилин',
    hours: 'годин',
    seconds: 'секунд',
    // Server-specific translations
    serverLimit: 'Ліміт серверів',
    noServersYet: 'Серверів поки немає',
    purchaseServersFromStore: 'Купуйте сервери в магазині, щоб почати хостинг та отримувати пасивний дохід!',
    visitServerStore: 'Відвідати магазин серверів',
    // Admin panel translations
    superAdminPanel: 'Супер адмін панель',
    adminPanel: 'Адмін панель', 
    totalUsers: 'Всього користувачів',
    onlineUsers: 'Онлайн користувачів',
    totalAdmins: 'Всього адмінів',
    adminManagement: 'Управління адмінами',
    selectUser: 'Вибрати користувача',
    chooseUser: 'Оберіть користувача',
    action: 'Дія',
    chooseAction: 'Оберіть дію',
    giveAdmin: 'Видати адмінку',
    removeAdmin: 'Забрати адмінку',
    banUser: 'Забанити користувача',
    unbanUser: 'Розбанити користувача',
    executeAction: 'Виконати дію',
    userList: 'Список користувачів',
    success: 'Успішно',
    error: 'Помилка',
    // Quest system
    dailyQuests: 'Щоденні завдання',
    achievements: 'Досягнення',
    rankings: 'Рейтинг',
    // Profile modal
    progressToLevel: 'Прогрес до рівня',
    xpNeeded: 'потрібно досвіду',
    totalEarnings: 'Загальний дохід',
    totalSpent: 'Витрачено загалом',
    netProfit: 'Чистий прибуток',
    jobsCompleted: 'Виконано робіт',
    coursesCompleted: 'Пройдено курсів',
    achievement: 'Досягнення',
    noAchievementsYet: 'Поки немає досягнень',
    earnAchievementsDesc: 'Виконуйте роботи та досягайте цілей, щоб отримати досягнення!',
    currentBalance: 'Поточний баланс',
    // Level up notification
    levelUp: 'Підвищення рівня!',
    levelUpCongrats: 'Вітаємо! Ви досягли рівня',
    newAbilitiesUnlocked: 'Нові можливості розблоковані!',
  },
  de: {
    tutorial: 'Tutorial',
    servers: 'Meine Server',
    hosting: 'Serverspeicher',
    learning: 'Lernzentrum',
    balance: 'Guthaben',
    income: 'Einkommen/min',
    serverLimit: 'Server-Limit',
    startJob: 'Job starten',
    completeJob: 'Job abschließen',
    purchaseServer: 'Server kaufen',
    deleteServer: 'Server löschen',
    toggleServer: 'Server umschalten',
    online: 'Online',
    offline: 'Offline',
    settings: 'Einstellungen',
    logout: 'Abmelden',
    login: 'Anmelden',
    register: 'Registrieren',
    nickname: 'Nickname',
    password: 'Passwort',
    confirmPassword: 'Passwort bestätigen',
    loggingIn: 'Anmeldung...',
    creatingAccount: 'Konto erstellen...',
    loginFailed: 'Anmeldung fehlgeschlagen',
    registrationFailed: 'Registrierung fehlgeschlagen',
    passwordsDoNotMatch: 'Passwörter stimmen nicht überein',
    heroTitle: 'Baue Dein Server-Imperium',
    heroSubtitle: 'Meistere die Kunst des Hostings',
    heroDescription: 'Beginne mit nichts und baue das größte Server-Hosting-Imperium in der virtuellen Welt auf. Meistere Wirtschaft, Technologie und Strategie.',
    startPlaying: 'Spielen Beginnen',
    learnMore: 'Mehr Erfahren',
    totalPlayers: 'Gesamtspieler',
    onlineNow: 'Jetzt Online',
    serversHosted: 'Server Gehostet',
    totalRevenue: 'Gesamtumsatz',
    gameFeatures: 'Spiel-Features',
    featuresDescription: 'Entdecke, was unseren Server-Hosting-Simulator einzigartig macht',
    feature1Title: 'Server Erstellen',
    feature1Desc: 'Erstelle und passe deine eigenen Server an',
    feature2Title: 'Globales Netzwerk',
    feature2Desc: 'Expandiere weltweit mit Rechenzentren',
    feature3Title: 'Umsatz Steigern',
    feature3Desc: 'Optimiere dein Geschäft für maximalen Gewinn',
    feature4Title: 'Hohe Leistung',
    feature4Desc: 'Biete blitzschnelle Hosting-Services',
    topPlayers: 'Top-Spieler',
    topPlayersDescription: 'Sieh, wer die Hosting-Branche dominiert',
    leaderboard: 'Rangliste',
    serversLowercase: 'Server',
    joinCompetition: 'An der Konkurrenz teilnehmen',
    allRightsReserved: 'Alle Rechte vorbehalten.',
    loginRegister: 'Anmelden / Registrieren',
    // Game interface elements
    start: 'Start',
    myServers: 'Meine Server',
    serverStore: 'Server-Shop',
    learningCenter: 'Lernzentrum',
    inProgress: 'In Bearbeitung',
    completed: 'Abgeschlossen',
    active: 'Aktiv',
    available: 'Verfügbar',
    unavailable: 'Nicht verfügbar',
    locked: 'Gesperrt',
    unlocked: 'Entsperrt',
    // Jobs and actions
    tutorialJobs: 'Tutorial-Aufgaben',
    startJob: 'Job starten',
    availableIn: 'Verfügbar in',
    earnMoney: '{amount} verdienen',
    cooldownTime: 'Abklingzeit: {time}',
    // Tutorial tips
    tutorialTips: 'Tutorial-Tipps',
    tipCompleteJobs: 'Führe Jobs aus, um Geld zu verdienen und Erfahrungen zu sammeln',
    tipJobCooldown: 'Jeder Job hat eine Abklingzeit, bevor du ihn erneut ausführen kannst',
    tipEarnToUnlock: 'Verdiene {amount}, um Server, Lernen und den Shop freizuschalten',
    tipPurchaseServers: 'Kaufe Server, um passives Einkommen zu generieren',
    tipTakeCourses: 'Belege Lernkurse, um mehr Server-Slots freizuschalten',
    browseServerStore: 'Server-Shop durchsuchen',
    browseLearningCourses: 'Lernkurse durchsuchen',
    // Activities
    recentActivities: 'Letzte Aktivitäten',
    // Tutorial completion
    tutorialCompleted: 'Tutorial abgeschlossen!',
    tutorialCompletedDesc: 'Herzlichen Glückwunsch! Du hast alle Spiel-Features freigeschaltet.',
    completeTutorialUnlock: 'Tutorial abschließen und alle Features freischalten',
    allFeaturesUnlocked: 'Alle Features freigeschaltet!',
    // Job types
    serverMaintenance: 'Server-Wartung',
    performanceOptimization: 'Leistungsoptimierung',
    securityAudit: 'Sicherheitsaudit',
    // Status indicators
    online: 'Online',
    offline: 'Offline',
    // Server products
    basicWebServer: 'Basic Web Server',
    highPerformanceServer: 'Hochleistungsserver',
    databaseServer: 'Datenbankserver',
    cdnServer: 'CDN-Server',
    webHosting: 'Web-Hosting',
    gamingApps: 'Gaming/Apps',
    storage: 'Speicher',
    contentDelivery: 'Content Delivery',
    // Learning courses
    basicServerSetup: 'Grundlegende Server-Einrichtung',
    advancedServerManagement: 'Erweiterte Server-Verwaltung',
    securityProtocols: 'Sicherheitsprotokolle',
    beginner: 'Anfänger',
    intermediate: 'Fortgeschritten',
    advanced: 'Experte',
    // Common UI elements
    close: 'Schließen',
    cancel: 'Abbrechen',
    confirm: 'Bestätigen',
    save: 'Speichern',
    edit: 'Bearbeiten',
    delete: 'Löschen',
    add: 'Hinzufügen',
    remove: 'Entfernen',
    update: 'Aktualisieren',
    refresh: 'Aktualisieren',
    loading: 'Laden...',
    // Time formats
    minutes: 'Minuten',
    hours: 'Stunden',
    seconds: 'Sekunden',
    // Server-specific translations
    serverLimit: 'Server-Limit',
    noServersYet: 'Noch keine Server',
    purchaseServersFromStore: 'Kaufe Server im Shop, um mit dem Hosting zu beginnen und passives Einkommen zu erzielen!',
    visitServerStore: 'Server-Shop besuchen',
    // Admin panel translations
    superAdminPanel: 'Super Admin Panel',
    adminPanel: 'Admin Panel', 
    totalUsers: 'Benutzer insgesamt',
    onlineUsers: 'Online-Benutzer',
    totalAdmins: 'Admins insgesamt',
    adminManagement: 'Admin-Verwaltung',
    selectUser: 'Benutzer auswählen',
    chooseUser: 'Benutzer wählen',
    action: 'Aktion',
    chooseAction: 'Aktion wählen',
    giveAdmin: 'Admin geben',
    removeAdmin: 'Admin entfernen',
    banUser: 'Benutzer bannen',
    unbanUser: 'Benutzer entbannen',
    executeAction: 'Aktion ausführen',
    userList: 'Benutzerliste',
    success: 'Erfolgreich',
    error: 'Fehler',
    // Quest system
    dailyQuests: 'Tägliche Aufgaben',
    achievements: 'Erfolge',
    rankings: 'Bestenliste',
    // Profile modal
    progressToLevel: 'Fortschritt zu Level',
    xpNeeded: 'XP benötigt',
    totalEarnings: 'Gesamteinkommen',
    totalSpent: 'Gesamt ausgegeben',
    netProfit: 'Nettogewinn',
    jobsCompleted: 'Abgeschlossene Jobs',
    coursesCompleted: 'Abgeschlossene Kurse',
    achievement: 'Erfolg',
    noAchievementsYet: 'Noch keine Erfolge',
    earnAchievementsDesc: 'Erledige Jobs und erreiche Meilensteine, um Erfolge zu erhalten!',
    currentBalance: 'Aktuelles Guthaben',
    // Level up notification
    levelUp: 'Level Aufstieg!',
    levelUpCongrats: 'Glückwunsch! Sie haben Level erreicht',
    newAbilitiesUnlocked: 'Neue Fähigkeiten freigeschaltet!',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('game-language') || 'en';
  });

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage);
    localStorage.setItem('game-language', newLanguage);
  };

  const value = {
    language,
    t,
    changeLanguage,
    localizeError: (error) => localizeError(error, language),
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
